version: '3.8'

services:
  mysql:
    image: mysql:8.0.32
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: agrixdb # Define o nome do banco de dados
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Monta o arquivo SQL dentro do contêiner MySQL

